# Generated by Django 6.0.4 on 2026-05-03 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_parcelamento_lancamento_parcelamento'),
    ]

    operations = [
        migrations.AddField(
            model_name='conta',
            name='legacy_id',
            field=models.PositiveIntegerField(blank=True, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='lancamento',
            name='legacy_id',
            field=models.PositiveIntegerField(blank=True, null=True, unique=True),
        ),
    ]
