# Generated by Django 6.0.4 on 2026-05-03 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_conta_legacy_id_lancamento_legacy_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='parcelamento',
            name='legacy_id',
            field=models.PositiveIntegerField(blank=True, null=True, unique=True),
        ),
    ]
