# Generated by Django 6.0.4 on 2026-05-03 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_parcelamento_legacy_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='conta',
            name='observacoes',
            field=models.TextField(blank=True, null=True),
        ),
    ]
