# Generated by Django 6.0.4 on 2026-05-03 20:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_conta_observacoes'),
    ]

    operations = [
        migrations.CreateModel(
            name='AgentePagador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('salario', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('info_bancaria', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='lancamento',
            name='agente_pagador',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lancamentos', to='core.agentepagador'),
        ),
    ]
