# Generated by Django 6.0.4 on 2026-05-03 22:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_agentepagador_lancamento_agente_pagador'),
    ]

    operations = [
        migrations.AddField(
            model_name='lancamento',
            name='transacao_id',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True),
        ),
    ]
