# Generated by Django 6.0.4 on 2026-05-03 23:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_lancamento_transacao_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='RegraImportacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('padrao', models.CharField(help_text='Termo contido no extrato (ex: UBER, IFOOD)', max_length=100)),
                ('nome_exibicao', models.CharField(blank=True, help_text='Nome amigável para o lançamento (opcional)', max_length=100)),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.categoria')),
            ],
            options={
                'verbose_name': 'Regra de Importação',
                'verbose_name_plural': 'Regras de Importação',
            },
        ),
    ]
