# Generated by Django 6.0.4 on 2026-05-04 00:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_regraimportacao'),
    ]

    operations = [
        migrations.AddField(
            model_name='categoria',
            name='tipo',
            field=models.CharField(choices=[('entrada', 'Entrada (Receita)'), ('saida', 'Saída (Gasto)')], default='saida', max_length=10),
        ),
    ]
