# Generated by Django 6.0.4 on 2026-05-04 00:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_categoria_tipo'),
    ]

    operations = [
        migrations.CreateModel(
            name='OfxArquivo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('arquivo', models.FileField(upload_to='ofx_imports/')),
                ('data_upload', models.DateTimeField(auto_now_add=True)),
                ('banco_nome', models.CharField(max_length=50)),
                ('agente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.agentepagador')),
            ],
        ),
        migrations.CreateModel(
            name='OfxTransacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fitid', models.CharField(max_length=255, unique=True)),
                ('data', models.DateField()),
                ('valor', models.DecimalField(decimal_places=2, max_digits=15)),
                ('descricao', models.TextField()),
                ('tipo', models.CharField(max_length=20)),
                ('status', models.CharField(choices=[('lido', 'Lido'), ('validado', 'Validado'), ('processado', 'Processado'), ('ignorado', 'Ignorado')], default='lido', max_length=20)),
                ('arquivo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transacoes', to='core.ofxarquivo')),
                ('conta_sugerida', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.conta')),
                ('lancamento_criado', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.lancamento')),
            ],
        ),
    ]
