# Generated by Django 6.0.4 on 2026-05-04 01:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_ofxarquivo_ofxtransacao'),
    ]

    operations = [
        migrations.AddField(
            model_name='ofxtransacao',
            name='categoria_manual',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.categoria'),
        ),
    ]
