# Generated by Django 6.0.4 on 2026-05-04 02:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_contabancaria_chavepix_ofxarquivo_conta_bancaria'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ofxtransacao',
            name='status',
            field=models.CharField(choices=[('lido', 'Lido'), ('validado', 'Validado'), ('processado', 'Processado'), ('ignorado', 'Ignorado'), ('transferencia', 'Transferência Interna')], default='lido', max_length=20),
        ),
    ]
