# Generated by Django 6.0.4 on 2026-05-04 02:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_alter_ofxtransacao_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ofxtransacao',
            name='lancamento_criado',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ofx_transacoes', to='core.lancamento'),
        ),
    ]
