# Generated by Django 6.0.4 on 2026-05-04 02:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_alter_ofxtransacao_lancamento_criado'),
    ]

    operations = [
        migrations.AddField(
            model_name='categoria',
            name='is_salary',
            field=models.BooleanField(default=False, help_text='Marque se esta categoria representa recebimento de salário'),
        ),
    ]
