# Generated by Django 6.0.4 on 2026-05-04 11:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_categoria_is_salary'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ofxtransacao',
            name='categoria_manual',
        ),
        migrations.RemoveField(
            model_name='regraimportacao',
            name='categoria',
        ),
        migrations.AddField(
            model_name='ofxtransacao',
            name='vinculo_por_regra',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='regraimportacao',
            name='conta',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='core.conta'),
            preserve_default=False,
        ),
    ]
