# Generated by Django 6.0.4 on 2026-05-07 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_remove_ofxtransacao_categoria_manual_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='parcelamento',
            name='lancamentos_extras',
            field=models.ManyToManyField(blank=True, related_name='parcelamentos_como_extra', to='core.lancamento'),
        ),
        migrations.AddField(
            model_name='parcelamento',
            name='valor_entrada',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='parcelamento',
            name='valor_parcela_final',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
