# Generated by Django 6.0.4 on 2026-05-07 15:00

import core.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_parcelamento_lancamentos_extras_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProdutoGarantia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255)),
                ('data_aquisicao', models.DateField()),
                ('valor', models.DecimalField(decimal_places=2, max_digits=10)),
                ('tempo_garantia', models.PositiveIntegerField(help_text='Quantidade de meses ou anos')),
                ('unidade_garantia', models.CharField(choices=[('meses', 'Meses'), ('anos', 'Anos')], default='meses', max_length=10)),
                ('nota_fiscal', models.FileField(blank=True, help_text='XML da NF-e ou PDF do DANFE', null=True, upload_to=core.models.upload_produto_doc_path)),
                ('contrato_garantia', models.FileField(blank=True, help_text='PDF do contrato de garantia', null=True, upload_to=core.models.upload_produto_doc_path)),
                ('lancamento', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='produtos', to='core.lancamento')),
                ('parcelamento', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='produtos', to='core.parcelamento')),
            ],
            options={
                'verbose_name': 'Produto e Garantia',
                'verbose_name_plural': 'Produtos e Garantias',
                'ordering': ['-data_aquisicao'],
            },
        ),
    ]
