# Generated by Django 6.0.4 on 2026-05-07 15:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_produtogarantia'),
    ]

    operations = [
        migrations.AddField(
            model_name='parcelamento',
            name='lancamento_entrada',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='parcelamento_entrada', to='core.lancamento'),
        ),
        migrations.AddField(
            model_name='parcelamento',
            name='lancamento_parcela_final',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='parcelamento_final', to='core.lancamento'),
        ),
    ]
