# Generated by Django 6.0.4 on 2026-05-07 15:15

import core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_parcelamento_lancamento_entrada_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='parcelamento',
            name='boleto',
            field=models.FileField(blank=True, null=True, upload_to=core.models.upload_parcelamento_boleto_path),
        ),
    ]
