from django.urls import path
from . import views

app_name = 'core'

urlpatterns = [
    path('', views.dashboard, name='dashboard'),
    path('conta/nova/', views.conta_create, name='conta_create'),
    path('conta/<int:pk>/editar/', views.conta_edit, name='conta_edit'),
    path('conta/<int:pk>/deletar/', views.conta_delete, name='conta_delete'),
    path('lancamento/novo/', views.lancamento_create, name='lancamento_create'),
    path('lancamento/<int:pk>/editar/', views.lancamento_edit, name='lancamento_edit'),
    path('lancamento/<int:pk>/deletar/', views.lancamento_delete, name='lancamento_delete'),
    path('pagamento/<int:pk>/registrar/', views.pagamento_registrar, name='pagamento_registrar'),
    path('relatorios/', views.relatorios, name='relatorios'),
    path('parcelamentos/', views.parcelamentos_list, name='parcelamentos_list'),
    path('parcelamentos/<int:pk>/editar/', views.parcelamento_edit, name='parcelamento_edit'),
    path('parcelamentos/<int:pk>/deletar/', views.parcelamento_delete, name='parcelamento_delete'),
    path('parcelamentos/<int:pk>/detalhe/', views.parcelamento_detalhe, name='parcelamento_detalhe'),
    path('parcelamentos/<int:pk>/associar-gasto/', views.parcelamento_associar_gasto, name='parcelamento_associar_gasto'),
    path('competencias/', views.competencias_list, name='competencias_list'),
    path('competencias/<int:pk>/reabrir/', views.competencia_reabrir, name='competencia_reabrir'),
    path('competencias/<int:pk>/exportar/', views.exportar_pdf, name='exportar_pdf'),
    path('configuracoes/', views.configuracoes, name='configuracoes'),
    path('importar/', views.importar_dados, name='importar_dados'),
    path('categoria/nova/', views.categoria_create, name='categoria_create'),
    path('categoria/<int:pk>/editar/', views.categoria_edit, name='categoria_edit'),
    path('categoria/<int:pk>/deletar/', views.categoria_delete, name='categoria_delete'),
    path('agente/novo/', views.agente_create, name='agente_create'),
    path('agente/<int:pk>/', views.agente_detail, name='agente_detail'),
    path('agente/<int:pk>/editar/', views.agente_edit, name='agente_edit'),
    path('agente/<int:pk>/deletar/', views.agente_delete, name='agente_delete'),
    
    # Banking management
    path('banco/novo/<int:agente_id>/', views.conta_bancaria_create, name='conta_bancaria_create'),
    path('banco/<int:pk>/editar/', views.conta_bancaria_edit, name='conta_bancaria_edit'),
    path('banco/<int:pk>/deletar/', views.conta_bancaria_delete, name='conta_bancaria_delete'),
    path('pix/novo/<int:conta_id>/', views.chave_pix_create, name='chave_pix_create'),
    path('pix/<int:pk>/deletar/', views.chave_pix_delete, name='chave_pix_delete'),
    path('regra/nova/', views.regra_create, name='regra_create'),
    path('regra/<int:pk>/editar/', views.regra_edit, name='regra_edit'),
    path('regra/<int:pk>/deletar/', views.regra_delete, name='regra_delete'),
    path('ofx/validar/', views.ofx_validar, name='ofx_validar'),
    path('ofx/reaplicar/', views.ofx_reaplicar_regras, name='ofx_reaplicar_regras'),
    path('ofx/vincular/<int:pk>/', views.ofx_vincular_conta, name='ofx_vincular_conta'),
    path('ofx/processar/', views.processar_vinculados, name='processar_vinculados'),
    path('ofx/limpar/', views.ofx_limpar_staging, name='ofx_limpar_staging'),
    path('ofx/update-categoria/<int:pk>/', views.ofx_update_categoria, name='ofx_update_categoria'),
    path('ofx/desvincular/<int:pk>/', views.ofx_desvincular, name='ofx_desvincular'),
    path('ofx/ignorar/<int:pk>/', views.ofx_ignorar_transacao, name='ofx_ignorar_transacao'),
    path('ofx/bulk-action/', views.ofx_bulk_action, name='ofx_bulk_action'),
    path('lancamento/<int:pk>/ofx-detalhes/', views.lancamento_ofx_detalhes, name='lancamento_ofx_detalhes'),
    path('legacy/migrate/conta/<int:legacy_id>/', views.legacy_migrate_conta, name='legacy_migrate_conta'),
    path('legacy/migrate/lancamento/<int:legacy_id>/', views.legacy_migrate_lancamento, name='legacy_migrate_lancamento'),
    path('legacy/migrate/competencia/<int:legacy_comp_id>/', views.legacy_migrate_competencia, name='legacy_migrate_competencia'),
    path('legacy/migrate/parcelamento/<int:legacy_id>/', views.legacy_migrate_parcelamento, name='legacy_migrate_parcelamento'),
    
    # Produtos, NF-e e Garantias
    path('produtos/', views.produtos_list, name='produtos_list'),
    path('produtos/<int:pk>/', views.produto_detalhe, name='produto_detalhe'),
    path('produtos/<int:pk>/editar/', views.produto_edit, name='produto_edit'),
    path('produtos/<int:pk>/deletar/', views.produto_delete, name='produto_delete'),
]
